### PR TITLE
chsgen: include logging code in debug mode

### PR DESCRIPTION
**Pull request by pohly**
When building in debug mode, the log.h header file references
code and (indirectly) libraries which we must add when linking
chsgen.

### CODE REVIEW

**Comment by OskarKinomoto** [comment]
Can you explain more? In chsgen all logs goes to cerr and log.h is not used.

**Comment by pohly** [comment]
To reproduce the problem, checkout 1.0.2 and try to build with -DCMAKE_BUILD_TYPE=DEBUG (what follows is from Debian Stable):

```
$ cd cynara
$ mkdir build
$ cd build
$ cmake -DCMAKE_BUILD_TYPE=DEBUG ..
...
$ cd src/chsgen
$ make
$ make
[ 25%] Building CXX object src/chsgen/CMakeFiles/cynara-db-chsgen.dir/ChecksumGenerator.cpp.o
[ 50%] Building CXX object src/chsgen/CMakeFiles/cynara-db-chsgen.dir/main.cpp.o
[ 75%] Building CXX object src/chsgen/CMakeFiles/cynara-db-chsgen.dir/__/common/log/Backtrace.cpp.o
[100%] Building CXX object src/chsgen/CMakeFiles/cynara-db-chsgen.dir/__/common/log/log.cpp.o
Linking CXX executable cynara-db-chsgen
[100%] Built target cynara-db-chsgen
pohly@pohly-desktop:/work/cynara/build/src/chsgen$ make clean
pohly@pohly-desktop:/work/cynara/build/src/chsgen$ make
-- Configuring done
-- Generating done
-- Build files have been written to: /work/cynara/build
Scanning dependencies of target cynara-db-chsgen
[ 50%] Building CXX object src/chsgen/CMakeFiles/cynara-db-chsgen.dir/ChecksumGenerator.cpp.o
[100%] Building CXX object src/chsgen/CMakeFiles/cynara-db-chsgen.dir/main.cpp.o
Linking CXX executable cynara-db-chsgen
CMakeFiles/cynara-db-chsgen.dir/ChecksumGenerator.cpp.o: In function `Cynara::Exception::Exception()':
/work/cynara/src/common/exceptions/Exception.h:33: undefined reference to `Cynara::Backtrace::getBacktrace()'
collect2: error: ld returned 1 exit status
src/chsgen/CMakeFiles/cynara-db-chsgen.dir/build.make:110: recipe for target 'src/chsgen/cynara-db-chsgen' failed
make[2]: *** [src/chsgen/cynara-db-chsgen] Error 1
CMakeFiles/Makefile2:404: recipe for target 'src/chsgen/CMakeFiles/cynara-db-chsgen.dir/all' failed
make[1]: *** [src/chsgen/CMakeFiles/cynara-db-chsgen.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
```

That shows  that ChecksumGenerator.cpp depends on code from src/common/log/Backtrace.cpp, which in turn depends on libdwf.

**Comment by zos** [comment]
@pohly Sorry, this is already fixed on tizen.org. We didn't update here for way too long. Chsgen won't be using Cynara::Exception classes at all, so adding dependencies won't be necessary.

**Comment by pohly** [comment]
Then please update here and close the issue as "fixed".

**Comment by zos** [comment]
Cynara has been updated.

**Comment by lukaszwojciechowski** [comment]
Missing functionality is already merged (patches pulled from tizen.org)

**Pull request closed without merging**
